# Written by: Christopher Gholmieh
# Constants:
declare -A secure_shell_parameters=(
    ["HostbasedAuthentication"]="no"
    ["PermitUserEnvironment"]="no"
    ["PasswordAuthentication"]="yes"
    ["PermitRootLogin"]="no"
    ["Protocol"]="2"
    ["PermitEmptyPasswords"]="no"
    ["GSSAPIAuthentication"]="no"
    ["ClientAliveInterval"]="15"
    ["ClientAliveCountMax"]="3"
    ["DisableForwarding"]="yes"
    ["AllowTcpForwarding"]="no"
    ["PermitRootLogin"]="no"
    ["LoginGracetime"]="60"
    ["X11Forwarding"]="no"
    ["IgnoreRhosts"]="yes"
    ["MaxAuthTries"]="3"
    ["MaxSessions"]="3"
    ["MaxStartups"]="10:30:60"
    ["LogLevel"]="VERBOSE"
    ["Ciphers"]="aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com"
    ["UsePAM"]="yes"
    ["Banner"]="/etc/issue.net"
    ["Port"]="5500"
)
